### ISSUE TITLE
演示用的Demo是有效的么？

### ISSUE THREAD

**Issue by zhangzw218** [EasyAbp/LoggingManagement#1]
我登录了https://logging.samples.easyabp.io/
尝试注册时候，没有看到任何内容
想知道，这个演示的Demo是有效的么？
![image](https://user-images.githubusercontent.com/40768649/191198337-1d5dfb3c-ffe8-4300-81b9-d65ca4c0b7c3.png)

**Comment by gdlcf88** [comment]
Sorry, the demo was added by mistake.

https://github.com/EasyAbp/LoggingManagement/commit/f6dd9ad566386bf13add68f70f9308d1bc55b9e2
